### ISSUE TITLE
Documentation  - Add preliminary documentation

### ISSUE THREAD

**Issue by regislon** [EPFL-ENAC/gpm_api#2]

**Comment by regislon** [comment]
@sphamba I think we can publish from our fork a dev readthedocs (on your account). And we will ask @ghiggi to do so from his repository to his readthedocs account. What do you think ?

**Comment by sphamba** [comment]
Otherwise, we can enable doc build for PRs: [like this](https://gpm-api--6.org.readthedocs.build/en/6/)
This could be sufficient, combined with local build of the doc when working on it. If you think it is not, I can indeed create a readthedoc entry with our fork.

**Comment by regislon** [comment]
Let's see with Ghiggi this morging
